# Generated by Django 2.1.4 on 2018-12-05 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20181205_2330'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookCopy',
            new_name='Book',
        ),
    ]
